# Generated by Django 4.2.30 on 2026-05-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('computer_science', 'Computer Science'), ('economics', 'Economics'), ('psychology', 'Psychology'), ('other', 'Other')], max_length=50)),
                ('custom_subject', models.CharField(blank=True, help_text='Fill this if subject is "Other"', max_length=100)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('phone_number', models.CharField(help_text='Include country code e.g. +1234567890', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable notifications for this session')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('start_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
