# Generated by Django 4.2.30 on 2026-05-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_conversationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('notification_type', models.CharField(choices=[('reminder', '5-min Reminder'), ('start', 'Session Start'), ('whatsapp_reply', 'WhatsApp Reply'), ('test', 'Test'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('dry_run', 'Dry Run (no credentials)')], max_length=10)),
                ('meta_message_id', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='timetable.studysession')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
